// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "./SYSTEM/delay/delay.h"

void btn_event_cb(lv_event_t* event)
{
    lv_event_code_t code = lv_event_get_code(event);
    lv_obj_t * obj = lv_event_get_target(event);
    lv_obj_t *lv_app_parent = lv_obj_get_parent(obj);

    if (code == LV_EVENT_CLICKED)
    {
			HAL_GPIO_TogglePin(GPIOB,GPIO_PIN_5);
       //HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,GPIO_PIN_SET);    /* PB5÷√1 */ 
        delay_ms(200);
//        HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,GPIO_PIN_RESET);  /* PB5÷√0 */
//        delay_ms(500); 
    }
}


void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);


    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	///////////tt
	lv_obj_add_event_cb(ui_Button1,btn_event_cb,LV_EVENT_CLICKED,NULL);
	

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 100);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_x(ui_TabView1, -179);
    lv_obj_set_y(ui_TabView1, 2);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 118);
    lv_obj_set_y(ui_Label1, -47);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 8);
    lv_obj_set_y(ui_Slider1, 87);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -92);
    lv_obj_set_y(ui_Switch1, 51);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);



}
